{
 "title": "OPNSense Firewall Events",
 "tags": [
  "elasticsearch",
  "OPNsense",
  "influxdb2",
  "telegraf"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "dataSource", "label": "InfluxDB", "query": "influxdb" },
   { "name": "ESdataSource", "label": "ElasticSearch", "query": "elasticsearch" },
   {
    "name": "Host",
    "label": "OPNsense",
    "query": "{\"find\": \"terms\", \"field\": \"source\", \"orderBy\": \"doc_count\"}"
   },
   {
    "name": "iface",
    "label": "FW_Interface",
    "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"interface\")\r\n  |> last()\r\n  |> group(columns: [\"tag\"])\r\n  |> keep(columns: [\"name\"])"
   },
   {
    "name": "src_geo_country",
    "label": "FW_Source geo",
    "query": "{\"find\": \"terms\", \"field\": \"src-ip-geo-country\", \"query\": \"interface:$iface\", \"timestamp\": {\n\"timestamp\" : \"now-$__Interval_ms\"\n}}"
   },
   {
    "name": "dst_geo_country",
    "label": "FW_Destination geo",
    "query": "{\"find\": \"terms\", \"field\": \"dst-ip-geo-country\", \"query\": \"interface:$iface\", \"timestamp\": {\n\"timestamp\" : \"now-$__Interval_ms\"\n}}"
   },
   {
    "name": "_helper_action",
    "query": "{\"find\": \"terms\", \"field\": \"action\", \"orderBy\": \"doc_count\"}"
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Action by Interface",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "interface",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "5" },
       "type": "terms"
      },
      {
       "field": "action",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "hide": false,
       "id": "1",
       "type": "count"
      }
     ],
     "query": "interface:$iface AND action:\"block\" AND source:$Host AND (src-ip-geo-country:$src_geo_country OR dst-ip-geo-country:$dst_geo_country)",
     "timeField": "timestamp"
    },
    {
     "bucketAggs": [
      {
       "field": "interface",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "5" },
       "type": "terms"
      },
      {
       "field": "action",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "hide": false,
       "id": "1",
       "type": "count"
      }
     ],
     "query": "interface:$iface AND action:\"pass\" AND source:$Host AND (src-ip-geo-country:$src_geo_country OR dst-ip-geo-country:$dst_geo_country)",
     "timeField": "timestamp"
    },
    {
     "bucketAggs": [
      {
       "field": "interface",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "5" },
       "type": "terms"
      },
      {
       "field": "action",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "hide": false,
       "id": "1",
       "type": "count"
      }
     ],
     "query": "interface:$iface AND action:\"nat\" AND source:$Host AND (src-ip-geo-country:$src_geo_country OR dst-ip-geo-country:$dst_geo_country)",
     "timeField": "timestamp"
    },
    {
     "bucketAggs": [
      {
       "field": "interface",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "5" },
       "type": "terms"
      },
      {
       "field": "action",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "hide": false,
       "id": "1",
       "type": "count"
      }
     ],
     "query": "interface:$iface AND action:\"rdr\" AND source:$Host AND (src-ip-geo-country:$src_geo_country OR dst-ip-geo-country:$dst_geo_country)",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Top Source Countries",
   "type": "piechart",
   "description": "Top 10 source countries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "src-ip-geo-country",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "interface:$iface AND source:$Host AND src-ip-geo-country:$src_geo_country",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Top Destination Countries",
   "type": "piechart",
   "description": "Top 10 destination countries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "dst-ip-geo-country",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "interface:$iface AND source:$Host AND dst-ip-geo-country:$dst_geo_country",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Event over time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "action",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "interface:$iface AND source:$Host AND (src-ip-geo-country:$src_geo_country OR dst-ip-geo-country:$dst_geo_country)",
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "Action by Interface", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "$_helper_action by Interface",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 22 },
   "repeat": "_helper_action",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "interface",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "interface:$iface AND action:$_helper_action AND source:$Host AND (src-ip-geo-country:$src_geo_country OR dst-ip-geo-country:$dst_geo_country)",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Events by Interface",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "interface",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      {
       "field": "action",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "interface:$iface AND source:$Host AND (src-ip-geo-country:$src_geo_country OR dst-ip-geo-country:$dst_geo_country)",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Source by Country",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "type": "piechart",
     "gridPos": { "h": 10, "w": 7, "x": 0, "y": 43 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "src-ip-geo-country",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "interface:$iface AND source:$Host AND src-ip-geo-country:$src_geo_country",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "type": "geomap",
     "gridPos": { "h": 10, "w": 17, "x": 7, "y": 43 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "src-ip-geo-country",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "interface:$iface AND source:$Host AND src-ip-geo-country:$src_geo_country",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 53 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "src-ip-geo-country",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "interface:$iface AND source:$Host AND src-ip-geo-country:$src_geo_country",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "$_helper_action by Country",
     "type": "piechart",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 63 },
     "repeat": "_helper_action",
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "src-ip-geo-country",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "interface:$iface AND source:$Host AND src-ip-geo-country:$src_geo_country AND action:$_helper_action",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Events by Country",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 73 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "src-ip-geo-country",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
         "type": "terms"
        },
        {
         "field": "action",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "interface:$iface AND source:$Host AND src-ip-geo-country:$src_geo_country",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Destination by Country",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "type": "piechart",
     "gridPos": { "h": 10, "w": 7, "x": 0, "y": 83 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "dst-ip-geo-country",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "interface:$iface AND source:$Host AND dst-ip-geo-country:$dst_geo_country",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "type": "geomap",
     "gridPos": { "h": 10, "w": 17, "x": 7, "y": 83 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "dst-ip-geo-country",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "interface:$iface AND source:$Host AND dst-ip-geo-country:$dst_geo_country",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 93 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "dst-ip-geo-country",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "interface:$iface AND source:$Host AND dst-ip-geo-country:$dst_geo_country",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "$_helper_action by Country",
     "type": "piechart",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 103 },
     "repeat": "_helper_action",
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "dst-ip-geo-country",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "interface:$iface AND source:$Host AND dst-ip-geo-country:$dst_geo_country AND action:$_helper_action",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Events by Country",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 113 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "dst-ip-geo-country",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
         "type": "terms"
        },
        {
         "field": "action",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "interface:$iface AND source:$Host AND dst-ip-geo-country:$dst_geo_country",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "$_helper_action by Source Country",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "repeat": "_helper_action",
   "collapsed": true,
   "panels": [
    {
     "type": "piechart",
     "gridPos": { "h": 10, "w": 7, "x": 0, "y": 45 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "src-ip-geo-country",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "interface:$iface AND action:$_helper_action AND source:$Host AND src-ip-geo-country:$src_geo_country",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "type": "geomap",
     "gridPos": { "h": 10, "w": 17, "x": 7, "y": 45 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "src-ip-geo-country",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "interface:$iface AND action:$_helper_action AND source:$Host AND src-ip-geo-country:$src_geo_country",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Action by Interface",
     "type": "piechart",
     "gridPos": { "h": 10, "w": 7, "x": 0, "y": 55 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "interface",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        }
       ],
       "metrics": [
        {
         "hide": false,
         "id": "1",
         "type": "count"
        }
       ],
       "query": "interface:$iface AND action:\"$_helper_action\" AND source:$Host AND (src-ip-geo-country:$src_geo_country OR dst-ip-geo-country:$dst_geo_country)",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 17, "x": 7, "y": 55 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "src-ip-geo-country",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "interface:$iface AND action:$_helper_action AND source:$Host AND src-ip-geo-country:$src_geo_country",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Events by Country",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 65 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "src-ip-geo-country",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
         "type": "terms"
        },
        {
         "field": "action",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "interface:$iface AND action:$_helper_action AND source:$Host AND src-ip-geo-country:$src_geo_country",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "$_helper_action by Destination Country",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "repeat": "_helper_action",
   "collapsed": true,
   "panels": [
    {
     "type": "piechart",
     "gridPos": { "h": 11, "w": 7, "x": 0, "y": 127 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "dst-ip-geo-country",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "interface:$iface AND action:$_helper_action AND source:$Host AND dst-ip-geo-country:$dst_geo_country",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "type": "geomap",
     "gridPos": { "h": 11, "w": 17, "x": 7, "y": 127 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "dst-ip-geo-country",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "interface:$iface AND action:$_helper_action AND source:$Host AND dst-ip-geo-country:$dst_geo_country",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "type": "heatmap",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 138 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "dst-ip-geo-country",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "interface:$iface AND action:$_helper_action AND source:$Host AND dst-ip-geo-country:$dst_geo_country",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Events by Country",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 149 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "dst-ip-geo-country",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
         "type": "terms"
        },
        {
         "field": "action",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "interface:$iface AND action:$_helper_action AND source:$Host AND dst-ip-geo-country:$dst_geo_country",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  }
 ]
}