{
 "title": "OPNsense Suricata",
 "tags": [
  "influxdb2",
  "telegraf",
  "OPNsense"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "dataSource", "label": "InfluxDB", "query": "influxdb" }
  ]
 },
 "panels": [
  {
   "title": "Suricata",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Top Alert Category",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"suricata\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"alert_category\")\r\n  |> map(fn: (r) => ({ r with _count: r[\"_value\"]}))\r\n  |> group(columns: [\"_value\"])\r\n  |> count(column: \"_count\")\r\n  |> group()\r\n  |> sort(desc:true, columns: [\"_count\"])\r\n  |> limit(n:1)"
    }
   ]
  },
  {
   "title": "Top Source IP",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"suricata\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"alert_category\")\r\n  |> map(fn: (r) => ({ r with _count: r[\"src_ip\"]}))\r\n  |> group(columns: [\"src_ip\"])\r\n  |> count(column: \"_count\")\r\n  |> group()\r\n  |> sort(desc:true, columns: [\"_count\"])\r\n  |> limit(n:1)"
    }
   ]
  },
  {
   "title": "Top 10 Destination Ports",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 7, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"suricata\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"alert_category\")\r\n  |> map(fn: (r) => ({ r with _count: r[\"dest_port\"]}))\r\n  |> group(columns: [\"dest_port\"])\r\n  |> count(column: \"_count\")\r\n  |> group()\r\n  |> sort(desc:true, columns: [\"_count\"])\r\n  |> limit(n: 10)"
    }
   ]
  },
  {
   "title": "Protocols",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"suricata\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"proto\")\r\n  |> map(fn: (r) => ({ r with _count: r[\"_value\"]}))\r\n  |> group(columns: [\"_value\"])\r\n  |> count(column: \"_count\")\r\n  |> group()\r\n  |> sort(desc:true, columns: [\"_count\"])"
    }
   ]
  },
  {
   "title": "Top Alert Signature",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"suricata\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"alert_signature\")\r\n  |> map(fn: (r) => ({ r with _count: r[\"_value\"]}))\r\n  |> group(columns: [\"_value\"])\r\n  |> count(column: \"_count\")\r\n  |> group()\r\n  |> sort(desc:true, columns: [\"_count\"])\r\n  |> limit(n:1)"
    }
   ]
  },
  {
   "title": "Top Destination IP",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"suricata\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"alert_category\")\r\n  |> map(fn: (r) => ({ r with _count: r[\"dest_ip\"]}))\r\n  |> group(columns: [\"dest_ip\"])\r\n  |> count(column: \"_count\")\r\n  |> group()\r\n  |> sort(desc:true, columns: [\"_count\"])\r\n  |> limit(n:1)"
    }
   ]
  },
  {
   "title": "Top 10 Alert Categories",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"suricata\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"alert_category\")\r\n  |> map(fn: (r) => ({ r with _count: r[\"_value\"]}))\r\n  |> group(columns: [\"_value\"])\r\n  |> count(column: \"_count\")\r\n  |> group()\r\n  |> sort(desc:true, columns: [\"_count\"])\r\n  |> limit(n:10)"
    }
   ]
  },
  {
   "title": "Top 10 Alert Signatures",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 14, "x": 10, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"suricata\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"alert_signature\")\r\n  |> map(fn: (r) => ({ r with _count: r[\"_value\"]}))\r\n  |> group(columns: [\"_value\"])\r\n  |> count(column: \"_count\")\r\n  |> group()\r\n  |> sort(desc:true, columns: [\"_count\"])\r\n  |> limit(n:10)"
    }
   ]
  },
  {
   "title": "Alert Logs",
   "type": "table",
   "description": "Last 100 events, newest on top",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"suricata\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"alert_signature\")\r\n  |> group()\r\n  |> sort(columns: [\"_time\"], desc: true)\r\n  |> limit(n:100)"
    }
   ]
  }
 ]
}